version: "2.2"
services:
  devssh:
    build: 
      context: .
      args:
        IMAGE: supervisely/agent
    ports:
      - "8888:22"
    volumes:
      - "./data:/data"
      - "./agent_data:/sly_agent"
      - "/var/run/docker.sock:/var/run/docker.sock"
