version: 3.9  # optional since v1.27.0
services:
  remote-dev:
    build: 
      args:
        IMAGE: supervisely/base-py
    ports:
      - 7777:22
    volumes:
      - ./data:/data
    container_name: app-debug

# docker-compose up -d